### ISSUE TITLE
[Compatibility] Trade Cycling

### ISSUE THREAD

**Issue by DoloSaber** [Ramixin/VisibleTraders#11]
When refreshing trades with Trade Cycling, only the first two transactions are shown.

![QQ截图20240825230946](https://github.com/user-attachments/assets/bc6eac34-1981-4d43-a1dd-c8275fb37660)

Only if you close the trading interface and right click villager again will all trades show up.

![QQ截图20240825231000](https://github.com/user-attachments/assets/a8a5ae2a-751e-4287-afd9-1bd74a6b16b9)

It's working fine, but can it get better, refresh all trades with Trade Cycling?
Sorry for issues again and again.

**Comment by DoloSaber** [comment]
Has this issue been resolved like Easy villagers ?

**Comment by Ramixin** [comment]
Hello @DoloSaber. The locked trades are generated over several ticks to prevent large lag spikes due to how inefficient the vanilla trade generation code is. I have set a limit on the locked trade generation so only 1 level's worth of trades is generated at a time. Because of that, all trade cycle mods send the updated trades too quickly for Visible Traders to be ready. It would not be efficient performance wise to have them all generate as well as feasible for me to add compats for each trade cycle mod since they all do it slightly differently

**Comment by Ramixin** [comment]
V:0.0.7 includes a hook for trade cycling mods to use for compat
