### ISSUE TITLE
Potential trade generation failure on multiplayer servers

### ISSUE THREAD

**Issue by AnaxyJod** [Ramixin/VisibleTraders#13]
Does this only work in single player ?
I tried it on a multiplayer server and it doesn't seems to be working

**Comment by Ramixin** [comment]
Hello @AnaxyJod , could you send a log through https://mclo.gs? This mod has been tested on multiplayer servers and it has worked.

**Comment by Ramixin** [comment]
Closed due to inactivity

**Comment by fallinlovv** [comment]
i am having the same problem on multiplayer server (paper)

**Comment by fallinlovv** [comment]
https://mclo.gs/6IE6JOJ
this is my latest log file

**Comment by Ramixin** [comment]
Hello @fallinlovv , Visible Traders is a fabric mod that is required on both the client and the server. This means that both the client and the server need the mod installed on both _as well as_ both being a fabric instance. Servers such as paper, bukkit, etc. Do not support mods (they support plugins). I would suggest switching away from paper and to a fabric server since 99% of plugins have a (better) mod version and also paper changes vanilla game mechanics just because they feel like it
