### ISSUE TITLE
[1.21.x][Neoforge] Mod causes Easy villagers to get wrong Trades 

### ISSUE THREAD

**Issue by ffuentesm** [Ramixin/VisibleTraders#7]
![image](https://github.com/user-attachments/assets/fd9d59a4-de66-46a4-aa89-bcd27b3ba029)
As you can see, the Cleric has armorer trades after level 2.

**Comment by Ramixin** [comment]
Thank you @ffuentesm for reaching out again. Visible Traders in no way changes how the trades are generated, which means Easy Villagers is lying to Minecraft for as to what trades need to be generated when it is installed. I will see if I can create a compatibility or not

**Comment by Ramixin** [comment]
@ffuentesm, I seem to be unable to find a specific way this could be happening. Could you please provide a detailed explanation as to how to reproduce this issue?

**Comment by ffuentesm** [comment]
Here is the video showing the problem. It mostly happens when you transfer a villager between professions. 
https://github.com/user-attachments/assets/a2f57480-b17c-48f6-8233-52e9a64329e9

**Comment by Ramixin** [comment]
@ffuentesm, this issue is sadly due to Easy Villagers not using the vanilla implementation of the Villager when inside of the block (primarily, the ticking aspect, which relates to #5 ). This issue will need to be resolved on their end. If you want, you can create an issue ticket on the Easy Villagers repo and link this issue. If the author of Easy Villagers is interesting in compatibility, I will update the mod to allow locked trades to be callable outside of the tick method and they will need to add a condition that calls this new method if Visible Traders is present

**Comment by henkelmax** [comment]
Hey @Ramixin, 
are you calculating future trades in the villagers tick method? Would there be a way I can somehow trigger this when rerolling the trades without having a dependency on your mod? Or would it be possible for you to call your method if the villagers trades change?

**Comment by Ramixin** [comment]
Thank you @henkelmax for responding. The locked trades are gradually calculated inside of the villager tick method. The mod automatically detects rerolls inside of the tick method as well. When I am able to get back to my computer, I will see If there are methods I could hook into that both vanilla ticking and your ticking use

**Comment by Ramixin** [comment]
@henkelmax , I added the trade generation logic to the `addAdditionalSaveData` method for the VillagerEntity which is used when ticking your trading block entity. After a little bit of testing, I can confirm the mods now work together properly and the trades are generated in a timely manner.

**Comment by henkelmax** [comment]
Nice, thank you!

**Comment by Ramixin** [comment]
Compat has been reverted due to the possibility for worlds to freeze when attempting to generate a map in the same chunk as a villager
